### ISSUE TITLE
Add AUC plot to drug screen module

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/shinyModules#10]

**Comment by apratap** [comment]
I dint get this one. AUC plot ??

**Comment by xindiguo** [comment]
Sara asked for the visualization of AUC in her original request. We only
have AUC value as filter right now.

-Xindi

*--*
*Xindi (Cindy) Guo*
Research Asscociate, Computational Oncology

Sage Bionetworks
Fred Hutchinson Cancer Research Center
1100 Fairview Ave North
Seattle, WA 98109
